export const TIPOS_MAQUINARIA = [
  "Acabado",
  "Acabado de cantos",
  "Acentar costura",
  "Acentar suela",
  "Activador",
  "Activador de Suela",
  "Activadora Inox.",
  "Aire acondicionado",
  "Almacen",
  "Apomazadora",
  "Apomazadora sencilla",
  "Aplicación de Estoperol",
  "Aplicador de Estoperoles",
  "Aplicador de Piedra",
  "Aplicar Cascos Soportes",
  "Aplicar Latex",
  "Aplicar estoperoles",
  "Aplicar estoperoles #1",
  "Aplicar estoperoles #2",
  "Aplicar estoperoles #3",
  "Aplicar estoperoles #10",
  "Aplicar hot glue spray",
  "Aplicar piedra Swarovski",
  "Asentar",
  "Asentar Costura",
  "Asentar Suela",
  "Asentar Suela (Avion)",
  "Asentar tubo de la bota",
  "Asentar tubo",
  "Banco con Brochuelos",
  "Banco con brochuelos con variador",
  "Banco de Cardado",
  "Banco de Cardar Enfranques",
  "Banco de Clavar",
  "Banco de Clavar Herradura",
  "Banco de Engrapar",
  "Banco de Lijas",
  "Banco de Lijas Cardas",
  "Banco de pulido de cantos",
  "Banco Enfranques",
  "Banco para acabar Calzado",
  "Banco para cardar, carrete y lijas",
  "Banco perforar",
  "Biselar Suela",
  "Bordadora",
  "Bordadora de 12 cabezas",
  "Bordar #3",
  "Bordar #4",
  "Bordar #5",
  "Bordar #6",
  "Bordar #7",
  "Bordar #8",
  "Brochuelo",
  "Brochuelo de dos estaciones con variador",
  "Brochuelo Sencillo",
  "Cabina calentamiento Cerco",
  "Cabina de aspreado para billeteras",
  "Cabina Ecologica",
  "Cabina Ecológica especial pieles",
  "Cabina Especial para Cintos",
  "Cabina quita Grapa",
  "Cambrear",
  "Capitoneado",
  "Cardar",
  "Chiller",
  "Chiller 5200",
  "Cizalla",
  "Clavadora",
  "Clavadora para fijar Planta",
  "Colector de Polvos",
  "Colocar boton",
  "Compresor",
  "Compresor de Aire",
  "Compresor de tornillo 20HP",
  "Congelador",
  "Conformar",
  "Conformar Talon",
  "Conformar Tubo",
  "Conveyor",
  "Coser suela",
  "Coser Suela",
  "Coser Welt",
  "Costear",
  "Costura",
  "Costura recta c/corte de hilo",
  "Costura recta c/palanca de retroceso",
  "Desbasurar",
  "Desvirar",
  "Desvirar Tacon",
  "Digitalizar",
  "Dividir",
  "Doblillar",
  "Domadora",
  "Domado",
  "Elevador",
  "Emplayadora",
  "Encementar",
  "Engrapadora Neumatica",
  "Ensortijadora",
  "Entaconar",
  "Entretelar",
  "Flameadora",
  "Flash Cut",
  "Flejadora",
  "Foliadora",
  "Fusionar",
  "Generador de luz",
  "Grabar",
  "Hormero",
  "Horno",
  "Horno de secado",
  "Horno Estabilizador",
  "Igualar Suela",
  "Laser",
  "Lijadora de Cantos",
  "Lizar Bordes",
  "Medir",
  "Mezclador",
  "Moldear",
  "Montar Talon",
  "Montar Enfranques",
  "Montar puntas",
  "Over Look",
  "Pegar Suela",
  "Pegar planta",
  "Perforar",
  "Pespuntar",
  "Pespunte",
  "Pintar Cantos",
  "Planchadora",
  "Plotter",
  "Polipasto",
  "Preacabar",
  "Prensar tacon",
  "Pulir",
  "Pulir Cantos",
  "Quitar emplaye",
  "Rebajar",
  "Rebajar Piel",
  "Rebatir Talon",
  "Recortar",
  "Recortar Suela",
  "Recortar Tubo",
  "Refilar",
  "Regulador",
  "Remachar",
  "Ribetear",
  "Robot",
  "Sacar Horma",
  "Sangrado",
  "Secador Activador",
  "Spaikear",
  "Taladro de Banco",
  "Tambor",
  "Tintar cantos",
  "Transformador",
  "Transportador",
  "Troquelar",
  "Vaporizador de cortes",
  "Voltear Tubo",
  "Yale"
].sort();

export const AREAS_OPERACION = [
  "Acabado",
  "Acabado L1",
  "Acabado L2",
  "Acabado Riel",
  "Avios",
  "Beta 7",
  "Billeteras",
  "Billeteras Lambda",
  "Chamarras",
  "Cinturones",
  "Corte",
  "Desarrollo",
  "Infraestructura",
  "Lambda",
  "Montado",
  "OMEGA",
  "Pespunte",
  "PT",
  "PT OMEGA",
  "Sala juntas accs",
  "Servicios",
  "Sigma",
  "Site",
  "VENTA",
  "Accesorios Lambda",
  "Acabado linea 2",
  "Administracion",
  "BAJA",
  "BILLETERAS",
  "Billeteras lambda",
  "BOLSAS",
  "CORTE",
  "Intemperie",
  "Maq. Fotonica",
  "PESPUNTE",
  "Planta Alta DESARROLLO",
  "Planta Alta DESUSO",
  "Planta Alta Mezannine ACC",
  "Planta Alta Mezannine PESPUNTE",
  "Planta Alta Mezannine PESPUNTE PRELIMINARES",
  "Planta Baja ACABADO",
  "Planta Baja ACC Beta 7",
  "Planta Baja AVIOS",
  "Planta Baja CORTE",
  "Planta Baja Mezannine ACC",
  "Planta Baja MONTADO",
  "planta alta operaciones",
  "Techumbre de acabado",
  "Techumbre de pespunte"
].sort();

export const PLANTAS = [
  "KAPPA",
  "OMEGA",
  "SIGMA",
  "LAMBDA",
  "GENERAL",
  "BAJA",
  "VENTA"
];
